branches:
  only:
  - python
language: python
python:
- pypy
- 2.6
- 2.7
- 3.3
# FIXME: uncomment the following line when Travis CI supports Python 3.4
#        https://github.com/travis-ci/travis-ci/issues/1989
#- 3.4
install:
- pip install -e . "Werkzeug >= 0.9"
script:
- python setup.py test
notifications:
  irc:
    channels:
    - "irc.ozinger.org:8080#hongminhee"
    on_success: change
    on_failure: always

